"""Add foto_perfil

Revision ID: ac4f99e783ac
Revises: 130ada31982f
Create Date: 2026-09-10 16:52:11.208338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac4f99e783ac'
down_revision: Union[str, None] = '130ada31982f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entregas_tareas', 'datos_respuesta',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_spanish_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'detalle_calificaciones',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_spanish_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('tareas', 'ejercicios_seleccionados',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_spanish_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('usuarios', sa.Column('foto_perfil', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'foto_perfil')
    op.alter_column('tareas', 'ejercicios_seleccionados',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_spanish_ci'),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'detalle_calificaciones',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_spanish_ci'),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'datos_respuesta',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_spanish_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
