"""add default to must_change_password

Revision ID: fb7bf0964615
Revises: ac4f99e783ac
Create Date: 2026-09-14 16:10:34.680460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb7bf0964615'
down_revision: Union[str, None] = 'ac4f99e783ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entregas_tareas', 'datos_respuesta',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'detalle_calificaciones',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('tareas', 'ejercicios_seleccionados',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('usuarios', 'foto_perfil',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_usuarios_carnet_universitario'), table_name='usuarios')
    op.drop_column('usuarios', 'carnet_universitario')
    op.drop_column('usuarios', 'must_change_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('must_change_password', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('carnet_universitario', mysql.VARCHAR(length=20), nullable=True))
    op.create_index(op.f('ix_usuarios_carnet_universitario'), 'usuarios', ['carnet_universitario'], unique=True)
    op.alter_column('usuarios', 'foto_perfil',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tareas', 'ejercicios_seleccionados',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'detalle_calificaciones',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'datos_respuesta',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
